title: Easy Hexo ğŸ‘¨â€ğŸ’»
description: è½»æ¾å…¥é—¨ Hexo
base: /
head:
  - type: link
    rel: icon
    href: /favicon.png
  - type: link
    rel: stylesheet
    href: https://cdn.jsdelivr.net/npm/octicons/build/font/octicons.css
  - type: link
    rel: stylesheet
    href: https://cdn.jsdelivr.net/npm/octicons/build/build.css
theme: macgs
themeConfig:
  valine:
    app_id: ESvDkjHus9gVRVp3CB6EsR1o-gzGzoHsz
    app_key: VxvYP7M4pOSCguXajHYCFWey
    notify: false
    verify: false
    avatar_cdn: https://sdn.geekzu.org/avatar/
    placeholder: ğŸ‘ æ¬¢è¿è¯„è®º~å¦‚æœ‰ç–‘é—®ï¼Œå¯åŠ ç¾¤ 935778924 è®¨è®º
    pageSize: 12
  nav:
    åº:
      åº: /0-Intro/
      é¡¹ç›®æˆå‘˜: /0-Intro/0-1-member.html
      ç‰¹åˆ«è‡´è°¢: /0-Intro/0-2-thanks.html
      å‚ä¸æœ¬é¡¹ç›®: /0-Intro/0-3-contributing.html
    Hexo å®‰è£…ä¸é…ç½®:
      æ¦‚è¦: /1-Hexo-install-and-config/
      è®¤è¯† Hexo: /1-Hexo-install-and-config/1-1-meet-hexo.html
      å®‰è£… Hexo: /1-Hexo-install-and-config/1-2-install-hexo.html
      é…ç½® Hexo: /1-Hexo-install-and-config/1-3-config-hexo.html
      éƒ¨ç½² Hexo: /1-Hexo-install-and-config/1-4-deploy-hexo.html
      æŒç»­é›†æˆ CI: /1-Hexo-install-and-config/1-5-continuous-integration.html
    ä¸»é¢˜å®‰è£…ä¸é…ç½®:
      æ¦‚è¦: /2-Theme-use-and-config/
      hexo-theme-ils: /2-Theme-use-and-config/2-2-hexo-theme-ils/
      hexo-theme-yilia: /2-Theme-use-and-config/2-3-hexo-theme-yilia/
      hexo-theme-apollo: /2-Theme-use-and-config/2-4-hexo-theme-apollo/
      hexo-theme-material: /2-Theme-use-and-config/2-5-hexo-theme-material/
      hexo-theme-volantis: /2-Theme-use-and-config/2-6-hexo-theme-volantis/
      hexo-theme-bmw: /2-Theme-use-and-config/2-7-hexo-theme-bmw/
      hexo-theme-aero-dual: /2-Theme-use-and-config/2-8-hexo-theme-aero-dual/
      hexo-theme-amber: /2-Theme-use-and-config/2-9-hexo-theme-amber/
      hexo-theme-indigo: /2-Theme-use-and-config/2-10-hexo-theme-indigo/
      hexo-theme-icarus: /2-Theme-use-and-config/2-12-hexo-theme-icarus/
      hexo-theme-fluid: /2-Theme-use-and-config/2-13-hexo-theme-fluid/
      hexo-theme-matery: /2-Theme-use-and-config/2-14-hexo-theme-matery/
      hexo-theme-stun: /2-Theme-use-and-config/2-16-hexo-theme-stun/
      hexo-theme-phantom: /2-Theme-use-and-config/2-17-hexo-theme-phantom/
      hexo-theme-archer: /2-Theme-use-and-config/2-18-hexo-theme-archer/
      hexo-theme-ayer: /2-Theme-use-and-config/2-19-hexo-theme-ayer/
    æ’ä»¶ä½¿ç”¨ä¸é…ç½®:
      æ¦‚è¦: /3-Plugins-use-and-config/
      hexo-tag-aplayer: /3-Plugins-use-and-config/3-1-hexo-tag-aplayer/
      hexo-tag-dplayer: /3-Plugins-use-and-config/3-2-hexo-tag-dplayer/
      hexo-helper-live2d: /3-Plugins-use-and-config/3-3-hexo-helper-live2d/
      hexo-blog-encrypt: /3-Plugins-use-and-config/3-4-hexo-blog-encrypt/
      hexo-tag-mmedia: /3-Plugins-use-and-config/3-5-hexo-tag-mmedia/
      hexo-submit-urls-to-search-engine: /3-Plugins-use-and-config/3-6-hexo-submit-urls-to-search-engine/
      hexo-filter-mathjax: /3-Plugins-use-and-config/3-7-hexo-filter-mathjax/
      hexo-tag-chart: /3-Plugins-use-and-config/3-8-hexo-tag-chart/
    é«˜çº§ Hexo ç©å®¶:
      æ¦‚è¦: /4-High-order-hexo-gamer/
      è®©ä½ çš„ Hexo åšå®¢æ”¯æŒè¿œç¨‹ç¼–è¾‘: /4-High-order-hexo-gamer/4-1-remote-editing/
      ç¼–å†™è‡ªå·±çš„ Hexo ä¸»é¢˜: /4-High-order-hexo-gamer/4-2-theme-develop/
    è¡¥å……å†…å®¹:
      æ¦‚è¦: /5-Add/
      å‚è€ƒèµ„æ–™: /5-Add/5-1-quote.html
      YAML è¯­æ³•ç®€ä»‹: /5-Add/5-2-yaml.html
      ä½¿ç”¨æ•°æ®æ–‡ä»¶å¹³æ»‘å‡çº§ä¸»é¢˜: /5-Add/5-3-data-file.html
  sidebar:
    /0-Intro/:
      - 0-1-member.html
      - 0-2-thanks.html
      - 0-3-contributing.html
    /1-Hexo-install-and-config/:
      - 1-1-meet-hexo.html
      - 1-2-install-hexo.html
      - 1-3-config-hexo.html
      - 1-4-deploy-hexo.html
      - 1-5-continuous-integration.html
    /2-Theme-use-and-config/:
      - 2-2-hexo-theme-ils/
      - 2-3-hexo-theme-yilia/
      - 2-4-hexo-theme-apollo/
      - 2-5-hexo-theme-material/
      - 2-6-hexo-theme-volantis/
      - 2-7-hexo-theme-bmw/
      - 2-8-hexo-theme-aero-dual/
      - 2-9-hexo-theme-amber/
      - 2-10-hexo-theme-indigo/
      - 2-12-hexo-theme-icarus/
      - 2-13-hexo-theme-fluid/
      - 2-14-hexo-theme-matery/
      - 2-16-hexo-theme-stun/
      - 2-17-hexo-theme-phantom/
      - 2-18-hexo-theme-archer/
      - 2-19-hexo-theme-ayer/
    /3-Plugins-use-and-config/:
      - 3-1-hexo-tag-aplayer/
      - 3-2-hexo-tag-dplayer/
      - 3-3-hexo-helper-live2d/
      - 3-4-hexo-blog-encrypt/
      - 3-5-hexo-tag-mmedia/
      - 3-6-hexo-submit-urls-to-search-engine/
      - 3-7-hexo-filter-mathjax/
      - 3-8-hexo-tag-chart/
    /4-High-order-hexo-gamer/:
      - 4-1-remote-editing/
      - 4-2-theme-develop/
    /5-Add/:
      - 5-1-quote.html
      - 5-2-yaml.html
      - 5-3-data-file.html
  repo: EasyHexo/Easy-Hexo
  repoLabel: GitHub
  docsDir: docs
  docsBranch: master
  editLinks: true
  editLinkText: åœ¨ GitHub ä¸Šç¼–è¾‘æ­¤é¡µ
